### ISSUE TITLE
Bug due to lookup server being down

### ISSUE THREAD

**Issue by PJGJ210** [toasty-toast/runelite-group-iron-panel#1]
When the lookup server is down the tab will output the failed string per below. 

Should add some logic to check if site returned an error and instead show an error message "down" or use a cached version of stats (stating also the server down). 

![image](https://user-images.githubusercontent.com/16944807/177678131-2ca2f4a1-a824-4598-892c-020e34820006.png)

**Comment by toasty-toast** [comment]
Thank you for submitting this issue. I am working on a fix and hope to have it deployed soon.

It seems this can happen when you launch the game and the Group Iron tab is selected in the friends/grouping menu but that menu has not been opened yet. Opening the Group Iron menu once should cause the client to load the group data and the plugin to detect the group properly again. 

![osrs-group-iron-bug](https://user-images.githubusercontent.com/9449195/178373639-e68460ff-af10-4927-ae0a-cce520979d7d.png)

In the next release of the plugin it will not overwrite the group members with junk data like it is doing here.

**Comment by PJGJ210** [comment]
Thanks for the information.
