### ISSUE TITLE
Plugin no longer in hub

### ISSUE THREAD

**Issue by jadedtdt** [toasty-toast/runelite-group-iron-panel#2]
Hi, I'm not able to see the group iron panel plugin anymore, do you have an ETA for when it will be fixed?

**Comment by toasty-toast** [comment]
Hey thank you for creating the issue and sorry for the delay in my reply!

I've submitted the update to the plugin hub and would expect it to become available in the next 24 hours.

**Comment by toasty-toast** [comment]
Back in the plugin hub as of this morning.
