### ISSUE TITLE
Levels not showing up for all members?

### ISSUE THREAD

**Issue by Redwards2** [toasty-toast/runelite-group-iron-panel#3]
My friends and I recently started an Ironman group and are all around level 30. For some reason one of the members levels will load when using the Group Iron Panel plugin but the other two wont. We aren't sure if this is due to too low of levels or what. Any help would be appreciated as we would love to utilize this great plug in!

![group iron panel 5 13 23](https://github.com/toasty-toast/runelite-group-iron-panel/assets/133527764/dd8051ba-d3ac-4fb3-a34a-34173d892379)

**Comment by toasty-toast** [comment]
Hello!

Yes from the info I could find you have to be in the top 2,000,000 players in any category before your player will show up in the hiscores. I searched on the RuneScape website and only the one player shows up there as well.

![image](https://github.com/toasty-toast/runelite-group-iron-panel/assets/9449195/b62a5253-759a-4267-a42a-44119f4108d3)
![image](https://github.com/toasty-toast/runelite-group-iron-panel/assets/9449195/0b4abc02-8a69-48a6-9c26-3e1d1fb6008c)
![image](https://github.com/toasty-toast/runelite-group-iron-panel/assets/9449195/60c20295-2dfb-40c6-b711-6bdbcb0f2705)

I think once you level up some more everyone should show up, but if that's not the case I'm happy to look into it further 😄

**Comment by Redwards2** [comment]
That was it! Thank you for taking time to look into it for us. Have a great day!
